GET {{baseUrl}}/courses HTTP/1.1

###

GET {{baseUrl}}/courses/{{courseId}} HTTP/1.1

###

POST {{baseUrl}}/courses HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "title3",
    "description": "description"
}